# Generated by Django 4.2.5 on 2023-10-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='questions_provided',
            field=models.BooleanField(default=False),
        ),
    ]
