# Generated by Django 4.2.5 on 2023-10-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_attempt_questions_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
