# Generated by Django 4.2.5 on 2023-09-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
