# Generated by Django 4.2.5 on 2023-09-26 01:07

import apps.assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.assessments.models.subcategory_image_upload, validators=[apps.assessments.models.image_file_size]),
        ),
    ]
