# Generated by Django 4.2.5 on 2023-10-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='user_difficulty_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
