# Generated by Django 4.2.5 on 2023-09-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_question_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentdifficultyrating',
            old_name='dificultad',
            new_name='difficulty',
        ),
    ]
