# Generated by Django 4.2.5 on 2023-10-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_user_difficulty_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='attempts_count',
            field=models.IntegerField(default=0),
        ),
    ]
