# Generated by Django 4.2.5 on 2023-10-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_points_userpoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpoints',
            options={'verbose_name_plural': 'User Points'},
        ),
    ]
