# Generated by Django 4.2.5 on 2023-10-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpoints_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
