# Generated by Django 4.1 on 2023-11-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
